concurrent = 1
check_interval = 0

[[runners]]
  name = "docker-builder-p8"
  url = "http://gitlab-server:30080/ci"
  token = "fa4cccbe6bf0486bbfdfec51e82927"
  executor = "docker"
  [runners.docker]
     tls_verify = false
     image = "my-local-registry:5000/theatre-builder-p8"
     privileged = true
     disable_cache = false
     shm_size = 0
     volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache", "/srv/pub:/var/ftp/pub"]
     extra_hosts = ["pvbook:192.168.1.3", "gitlab-server:192.168.1.3"]
  [runners.cache]

[[runners]]
  name = "vstand p8"
  url = "http://gitlab-server:30080/ci"
  token = "5edebc4ca031882b631eb23a912728"
  environment = ["TERM=xterm"]
  executor = "shell"
