#!/bin/sh

module_usage()
{
	echo "gitlab-ci NOT YET!"
}

module_help()
{
	echo "gitlab-ci NOT YET!"
}

[ -z "$1" ] && module_help && exit 1

case $1 in
    -h|--help|help)
        module_help
        exit 0
        ;;
    --usage|usage)
        module_usage
        exit 0
        ;;
esac            

echo "Run gitlab-ci $@"
