# Конфигурирование виртуального стенда (vbox машины)
# --------------------------------------------------------------------
- hosts: all
  become: yes
  gather_facts: no 
  vars_files:
     - "{{ daas_vstand_config }}"
     - "{{ daas_project_config }}"
     - "{{daas_ansible_dir}}/daas-defaults.yml"
     # обязательно должен быть последним (т.к. переопределяет свойства проекта и умолчательные настройки)
     - "{{daas_ansible_dir}}/daas-vstand-config.yml"

  vars:
    ansible_ssh_user: "{{daas_vstand.user}}"
    ansible_ssh_password: "{{daas_vstand.pass}}"

  pre_tasks:
     - name: 'setup password for ssh user'
       set_fact: ansible_ssh_pass="{{ daas_vstand.pass }}"
       tags: 
         - gitlab
         - daas
         - user-setup         
         - install
         - consul
         - net

     - name: 'install python'
       raw: "if ! rpm -qa | grep -q 'python-module-simplejson'; then apt-get update && apt-get -y install python-module-simplejson python-module-distutils-extra; fi"
       tags: 
         - gitlab
         - daas
         - user-setup         
         - install
         - consul
         - net

  tasks:

    #  - debug: var=vars
    #  - shell: /bin/false

     - name: configure vstand for "{{ project.name }}"
       include: "{{daas_ansible_dir}}/playbooks/vstand-setup-tasks.yml"

     - name: configure consul for vstand of "{{ project.name }}"
       include: "{{daas_ansible_dir}}/playbooks/vstand-setup-consul-tasks.yml"
