# Настройка vbox-машины под конкретный проект
# --------------------------------------------------------------------
- name: use config file for stand
  debug: msg="{{ daas_vars_files }}"
  tags: tt

- name: use project file
  debug: msg="{{ daas_project_file }}"
  tags: tt

- name: use project name
  debug: msg="{{ project.name }}"
  tags: tt

- name: install programs
  apt_rpm: "package={{item}} state=present"
  with_items:
    - mc
    - wget 
    - htop
    - curl
    - eepm
    - apt-repo
    - docker-ce
    - python-module-docker
    - python-module-pip
    - python-module-jinja2
    - cgroup 
    - iptables
    - git-core
    - etersoft-build-utils
    - etcgit
    - su

- name: control su
  shell: control su public

- name: install docker-compose
  pip: name=docker-compose

- name: "add {{ project.vstand.user }} to group 'docker'"
  user:
    name: "{{ project.vstand.user }}"
    groups: docker
    append: yes

- name: install daas from package
  apt_rpm: "package={{item}} state=present"
  when: vstand.daas_url is undefined
  tags: 
    - daas

- name: copy daas from local file
  copy:
    src: "{{vstand.daas_url}}"
    dest: "/tmp/"
  when: vstand.daas_url is defined and 'http' not in vstand.daas_url
  tags: 
    - daas

- name: load daas from url
  get_url:
    url: "{{vstand.daas_url}}"
    dest: /tmp/
  when: vstand.daas_url is defined and 'http' in vstand.daas_url
  tags: 
    - daas

- name: "install daas from local package"
  shell: "rpm -qa | grep -q daas || sudo epmi --auto /tmp/daas*.rpm"
  when: vstand.daas_url is defined
  tags: 
    - daas

- name: "remove daas local package"
  shell: rm -rf /tmp/daas*.rpm
  when: vstand.daas_url is defined
  tags: 
    - daas

- name: download gitlab-runner from internet
  get_url:
    url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
    dest: /usr/local/bin/gitlab-runner
    mode: 'a+x'
  when: vstand.gitlab.runner_download_url is undefined or vstand.gitlab.runner_download_url|length == 0
  tags: 
    - gitlab

- name: copy gitlab-runner from local file
  copy:
    dest: /usr/local/bin/gitlab-runner
    src: "{{vstand.gitlab.runner_download_url}}"
    mode: 'a+x'
  when: vstand.gitlab.runner_download_url is defined and 'http' not in vstand.gitlab.runner_download_url
  tags: 
    - gitlab

- name: download gitlab-runner from url
  get_url:
    url: "{{vstand.gitlab.runner_download_url}}"
    dest: /usr/local/bin/gitlab-runner
    mode: 'a+x'
  when: vstand.gitlab.runner_download_url is defined and 'http' in vstand.gitlab.runner_download_url 
  tags: 
    - gitlab

- name: create gitlab-runner service file
  template: "src={{daas_ansible_dir}}/templates/gitlab-runner.service.tpl dest=/etc/systemd/system/gitlab-runner.service owner=root"
  tags: 
    - gitlab

- name: List configured runners
  become: no
  command: gitlab-runner list --config '/home/{{project.vstand.user}}/.gitlab-runner/config.toml'
  register: configured_runners
  changed_when: False
  tags: 
    - gitlab

- name: Register runners to GitLab
  become: no
  command: gitlab-runner register >
    --config '/home/{{project.vstand.user}}/.gitlab-runner/config.toml'
    --non-interactive
    --url '{{ vstand.gitlab.url }}'
    --registration-token '{{ gitlab_runner_registration_token }}'
    --description '{{ item.runner.description }}'
    --tag-list '{{ item.runner.tags if item.runner.tags is defined else '' }}'
    --executor '{{ item.runner.executor }}'
    --docker-image '{{ item.runner.docker_image if item.runner.docker_image is defined else '' }}'
    --env 'TERM=xterm'
    {{ item.runner.extra_options if item.runner.extra_options is defined else '' }}
  when: "item.runner.description is defined and configured_runners.stderr.find('\n{{ item.runner.description }}') == -1" 
  with_items: "{{vstand.gitlab.runners}}"
  tags: 
    - gitlab

- name: Start gitlab-runner service
  service: name=gitlab-runner state=started enabled=yes
  tags: 
    - gitlab

- name: create rpmmacros
  become: no
  template: "src={{daas_ansible_dir}}/templates/rpmmacros.tpl dest=/home/{{project.vstand.user}}/.rpmmacros"
