# Конфигурирование виртуального стенда (vbox машины)
# --------------------------------------------------------------------
- hosts: all
  become: yes
  gather_facts: no 
  vars_files:
     - "{{ daas_vars_files }}"
     - "{{ daas_project_file }}"

  vars:
    ansible_ssh_user: "{{project.vstand.user}}"
    ansible_ssh_password: "{{project.vstand.pass}}"
    gitlab_runner_registration_token: "{{ vstand.gitlab.runner.registration_token }}"

  pre_tasks:
     - name: 'set password for ssh user'
       set_fact: ansible_ssh_pass="{{ project.vstand.pass }}"
       tags: 
         - gitlab
         - daas

     - name: 'install python'
       raw: "if ! rpm -qa | grep -q 'python-module-simplejson'; then sudo apt-get update && sudo apt-get -y install python-module-simplejson python-module-distutils-extra; fi"
       tags: 
         - gitlab
         - daas

  tasks:
     - name: configure vstand for "{{ project.name }}"
       include: "{{daas_ansible_dir}}/playbooks/vstand-setup-tasks.yml"
