---
# Настройка мониторинга (netdata + grafana + influxdb + nginx)
# --------------------------------------------------------------------
- name: install monitoring services
  apt_rpm: "package={{item}} state=present update_cache=no"
  with_items:
    - netdata
    - influxdb
    - grafana
    - sqlite3
    - nginx
  tags:
    - monitoring

- name: make config for influxdb
  template:
    src: "{{ daas_ansible_dir }}/templates/influxdb.conf.tpl"
    dest: "/etc/influxdb/influxdb.conf"
    owner: root
    group: influxdb
    mode: 0640
    backup: yes
  tags:
    - monitoring

- name: Start influxdb service
  service: name=influxdb state=started enabled=yes
  tags:
    - monitoring

- name: make config for netdata
  template:
    src: "{{ daas_ansible_dir }}/templates/netdata.conf.tpl"
    dest: "/etc/netdata/netdata.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  tags:
    - monitoring

- name: Start netdata service
  service: name=netdata state=started enabled=yes
  tags:
    - monitoring

- name: make config for nginx
  template:
    src: "{{ daas_ansible_dir }}/templates/nginx.conf.tpl"
    dest: "/etc/nginx/sites-enabled.d/vstand.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  tags:
    - monitoring

- name: make config for nginx
  template:
    src: "{{ daas_ansible_dir }}/templates/nginx.conf.tpl"
    dest: "/etc/nginx/sites-enabled.d/vstand.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  tags:
    - monitoring

- name: create nginx services dir
  file: "path=/etc/nginx/services.d state=directory mode=0777"
  tags:
    - monitoring

- name: make config for nginx
  template:
    src: "{{ daas_ansible_dir }}/templates/{{item}}.tpl"
    dest: "/etc/nginx/services.d/{{item}}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_items:
    - netdata-location.conf
    - netdata-upstream.conf
    - grafana-location.conf
    - grafana-upstream.conf
  tags:
    - monitoring

- name: Start nginx service
  service: name=nginx state=started enabled=yes
  tags:
    - monitoring

- name: make config for grafana
  template:
    src: "{{ daas_ansible_dir }}/templates/grafana.ini.tpl"
    dest: "/etc/grafana/grafana.ini"
    owner: root
    group: grafana
    mode: 0640
    backup: yes
  tags:
    - monitoring

- name: create grafana data sources dir
  file: "path=/etc/grafana/provisioning/datasources/ group=grafana owner=grafana state=directory mode=0775"
  tags:
    - monitoring

- name: make datasources for grafana
  template:
    src: "{{ daas_ansible_dir }}/templates/grafana-datasources.tpl"
    dest: "/etc/grafana/provisioning/datasources/vstand.yaml"
    owner: grafana
    group: grafana
    mode: 0640
    backup: yes
  tags:
    - monitoring

- name: make dashboards for grafana
  template:
    src: "{{ daas_ansible_dir }}/templates/grafana-dashboards.tpl"
    dest: "/etc/grafana/provisioning/dashboards/vstand-dashboards.yaml"
    owner: grafana
    group: grafana
    mode: 0640
    backup: yes
  tags:
    - monitoring

- name: create directory for grafana dashboards
  file: "path=/var/lib/grafana/dashboards group=grafana owner=grafana state=directory mode=0775"
  tags:
    - monitoring

- name: make dashboards for grafana
  template:
    src: "{{ daas_ansible_dir }}/templates/{{item}}.tpl"
    dest: "/var/lib/grafana/dashboards/{{item}}"
    owner: grafana
    group: grafana
    mode: 0644
    backup: yes
  with_items:
    - grafana-dashboard-netdata.json
  tags:
    - monitoring

- name: Start grafana service
  service: name=grafana-server state=started enabled=yes
  tags:
    - monitoring
