# Вывод на экран итоговой конфигурации
# --------------------------------------------------------------------
- hosts: all
  become: yes
  gather_facts: no
  vars_files:
     - "{{ daas_vstand_config }}"
     - "{{ daas_project_config }}"
     - "{{daas_ansible_dir}}/daas-defaults.yml"

  tasks:
     - name: show default config (daas_defaults)
       debug: msg="{{daas_defaults}}"
