# Конфигурирование виртуального стенда (vbox машины)
# --------------------------------------------------------------------
- hosts: all
  become: yes
  gather_facts: no 
  vars_files:
     - "{{ daas_vars_files }}"
     - "{{ daas_project_file }}"

  vars:
    ansible_ssh_user: "{{project.vstand.user}}"
    ansible_ssh_password: "{{project.vstand.pass}}"

  pre_tasks:
     - name: 'set password for ssh user'
       set_fact: ansible_ssh_pass="{{ project.vstand.pass }}"
       tags: tt

     - name: 'install python'
       raw: "rpm -qa | grep -q 'python-module-simplejson' || apt-get -y install python-module-simplejson python-module-distutils-extra"

  tasks:
     - name: prepare..
       include: "{{daas_ansible_dir}}/playbooks/vstand-setup-tasks.yml"
