---
# Final vstand config 
# (merge project config and user vstand config and defaults)
daas_vstand:

  # Parameters for virtual stand (hostname,user,pass)
  hostname: "{{ user_hostname if user_hostname is defined 
              else vstand.hostname 
              if vstand is defined 
              and vstand.hostname is defined 
              else daas_defaults.vstand.hostname }}"
  user: "{{ vstand_user_login if vstand_user_login is defined
            else vstand.user 
            if vstand is defined 
            and vstand.user is defined 
            else daas_defaults.vstand.user }}"

  pass: "{{ vstand_user_pass if vstand_user_pass is defined
            else vstand.pass 
            if vstand is defined 
            and vstand.pass is defined 
            else daas_defaults.vstand.pass }}"

  # first a user DNS servers, and then the default
  dns_servers: "{{ user_dns_servers 
                    if user_dns_servers is defined 
                    else [] }}
                + {{ vstand.dns_servers 
                    if vstand is defined 
                    and vstand.dns_servers is defined
                    else [] }}
                + {{ daas_defaults.vstand.dns_servers 
                    if daas_defaults.vstand is defined
                    and daas_defaults.vstand.dns_servers is defined else [] }}"

  # Parameters for host machine for vstands (hostname,user,pass)
  hostmachine:
    hostname: "{{ hostmachine_hostname if hostmachine_hostname is defined
              else vstand.hostmachine.hostname 
              if vstand is defined 
              and vstand.hostmachine is defined 
              and vstand.hostmachine.hostname is defined 
              else daas_defaults.hostmachine.hostname }}"
    user: "{{ hostmachine_user_login if hostmachine_user_login is defined
              else vstand.hostmachine.user 
              if vstand is defined 
              and vstand.hostmachine is defined 
              and vstand.hostmachine.user is defined 
              else daas_defaults.hostmachine.user }}"

    pass: "{{ hostmachine_user_pass if hostmachine_user_pass is defined
              else vstand.hostmachine.pass 
              if vstand is defined 
              and vstand.hostmachine is defined 
              and vstand.hostmachine.pass is defined 
              else daas_defaults.hostmachine.pass }}"
              
    pub_interface: "{{ vstand.hostmachine.pub_interface 
              if vstand is defined 
              and vstand.hostmachine is defined
              and vstand.hostmachine.pub_interface is defined 
              else daas_defaults.hostmachine.pub_interface }}"
              
  # limits for virtual stand for project
  limits:
    cpu: "{{ vstand.limits.cpu 
            if vstand is defined 
            and vstand.limits is defined 
            and vstand.limits.cpu is defined 
            else daas_defaults.vstand.limits.cpu }}"
            
    memory: "{{ vstand.limits.memory 
            if vstand is defined 
            and vstand.limits is defined 
            and vstand.limits.memory is defined 
            else daas_defaults.vstand.limits.memory }}"
    
  # Parameters for vagrant
  vagrant:
    rpm_url: "{{ vstand.vagrant.rpm_url 
            if vstand is defined 
            and vstand.vagrant is defined 
            and vstand.vagrant.rpm_url is defined 
            else daas_defaults.vagrant.rpm_url }}"
    patch: "{{ vstand.vagrant.patch 
            if vstand is defined 
            and vstand.vagrant is defined 
            and vstand.vagrant.patch is defined 
            else daas_defaults.vagrant.patch }}"
    box:  
      name: "{{ vstand.vagrant.box.name 
                if vstand is defined 
                and vstand.vagrant is defined
                and vstand.vagrant.box is defined 
                and vstand.vagrant.box.name is defined 
                else daas_defaults.vagrant.box.name }}"
      url: "{{ vstand.vagrant.box.url 
                if vstand is defined 
                and vstand.vagrant is defined
                and vstand.vagrant.box is defined 
                and vstand.vagrant.box.url is defined 
                else daas_defaults.vagrant.box.url }}"
      add_args: "{{ vstand.vagrant.box.add_args 
                if vstand is defined 
                and vstand.vagrant is defined
                and vstand.vagrant.box is defined 
                and vstand.vagrant.box.add_args is defined 
                else daas_defaults.vagrant.box.add_args }}"

  # Parameters for gitlab
  gitlab:
    url: "{{ vstand.gitlab.url 
             if vstand is defined 
             and vstand.gitlab is defined
             and vstand.gitlab.url is defined 
             else daas_defaults.gitlab.url }}"
    
    runner_registration_token: "{{ vstand.gitlab.runner_registration_token 
             if vstand is defined 
             and vstand.gitlab is defined
             and vstand.gitlab.runner_registration_token 
             is defined else '' }}"
             
    runner_download_url: "{{ vstand.gitlab.runner_download_url 
             if vstand is defined 
             and vstand.gitlab is defined
             and vstand.gitlab.runner_download_url is defined 
             else daas_defaults.gitlab.runner_download_url }}"
             
    runners: "{{ vstand.runners 
             if vstand is defined 
             and vstand.runners is defined 
             else daas_defaults.gitlab.runners }}"

  daas_url: "{{ project.daas_url 
               if project is defined 
               and project.daas_url is defined 
               else daas_defaults.daas_url }}"

  consul:
     url: "{{ vstand.consul.url 
               if vstand is defined 
               and vstand.consul is defined 
               and vstand.consul.url is defined 
               else daas_defaults.consul.url }}"

     user:  "{{ vstand.consul.user 
               if vstand is defined 
               and vstand.consul is defined 
               and vstand.consul.user is defined 
               else daas_defaults.consul.user }}"

     mode:  "{{ vstand.consul.mode 
               if vstand is defined 
               and vstand.consul is defined 
               and vstand.consul.mode is defined 
               else daas_defaults.consul.mode }}"

     bind:  "{{ vstand.consul.bind 
               if vstand is defined 
               and vstand.consul is defined 
               and vstand.consul.bind is defined 
               else daas_defaults.consul.bind }}"

     dc:  "{{ vstand.consul.dc 
               if vstand is defined 
               and vstand.consul is defined 
               and vstand.consul.dc is defined 
               else daas_defaults.consul.dc }}"

     log_level:  "{{ vstand.consul.log_level
               if vstand is defined 
               and vstand.consul is defined 
               and vstand.consul.log_level is defined 
               else daas_defaults.consul.log_level }}"

     dns_servers: "{{ user_dns_servers 
                    if user_dns_servers is defined 
                    else [] }}
                + {{ vstand.dns_servers 
                    if vstand is defined 
                    and vstand.dns_servers is defined
                    else [] }}
                + {{ vstand.consul.dns_servers 
                    if vstand is defined 
                    and vstand.consul is defined 
                    and vstand.consul.dns_servers is defined
                    else [] }}
                + {{ daas_defaults.consul.dns_servers 
                      if daas_defaults.consul.dns_servers is defined else [] }}
                + {{ daas_defaults.vstand.dns_servers 
                    if daas_defaults.vstand is defined
                    and daas_defaults.vstand.dns_servers is defined else [] }}"    

     servers: "{{ user_consul_servers 
                  if user_consul_servers is defined else [] }}
                + {{ vstand.consul.servers 
                    if vstand is defined 
                    and vstand.consul is defined 
                    and vstand.consul.servers is defined
                    else [] }}
                + {{ daas_defaults.consul.servers 
                   if daas_defaults.consul.servers is defined else [] }}"
                    

     extra_args:  "{{ vstand.consul.extra_args
               if vstand is defined 
               and vstand.consul is defined 
               and vstand.consul.extra_args is defined 
               else daas_defaults.consul.extra_args }}"

  apt:
    sources: "{{ daas_defaults.vstand.apt.sources 
                  if daas_defaults.vstand.apt.sources is defined 
                  else [] }}
                + 
              {{ vstand.apt.sources 
                    if vstand is defined 
                    and vstand.apt is defined 
                    and vstand.apt.sources is defined
                    else [] }}"

    packages: "{{ daas_defaults.vstand.apt.packages 
                  if daas_defaults.vstand.apt.packages is defined 
                  else [] }}
                +
               {{ vstand.apt.packages 
                    if vstand is defined 
                    and vstand.apt is defined 
                    and vstand.apt.packages is defined 
                    else [] }}"

  ntpd:
    servers: "{{ vstand.ntpd.servers 
                if vstand is defined 
                and vstand.ntpd is defined
                and vstand.ntpd.servers is defined 
                else daas_defaults.ntpd.servers }}"
