#!/bin/sh

datadir=.

export DAAS_DATADIR=${datadir}

CMD="$1"

usage()
{
    echo "daas module [command] parameters"
    echo ""
    echo "Use: daas module -h|--help|usage - for help module commands"
    echo ""
    echo "Available modules:"
    echo "------------------"
    MODULES=$( find ${datadir}/modules.d/ -maxdepth 1 -type f -and -not -name '.*' )
    for m in $MODULES;
    do
	echo $(basename "$m")
    done
}

[ -z "$CMD" ] && usage && exit 1

case $CMD in
    -h|--help|help)
        usage
        ;;
esac

if ! test -f "${DAAS_DATADIR}/modules.d/$CMD"; then
    echo "Unknown command '$CMD'. Use -h|--help for help"
    exit 1
fi

shift
exec $DAAS_DATADIR/modules.d/$CMD $@
