---
version: 0.1

vstand:
  hostmachine:
    hostname: "vstand1"
    user: "vagrant"
    pass: "123"

  hostname: "{{project.name}}-vs1"
  dns_servers:
     - "172.17.0.2"
     
  consul:
     servers:
       - "172.17.0.2"

  limits:
    cpu: 3
    memory: 1024 
    
  vagrant:
     box: 
       name: "vstand-p8"
       url: "{{ daas_data_dir }}/vstand/vagrant/boxes/p8/vstand.box"

  gitlab:
    url: "http://192.168.1.76:30080/"
    runner_registration_token: "xsmZtVJpEhbuxTp1JAys"
    runner_download_url: "{{ daas_ansible_dir}}/addons/gitlab-runner-linux-amd64"
