---
version: 0.1

vstand:
  pass: "123"

  hostmachine:
    hostname: "vstand1"
    user: "vadmin"
    pass: "123"

  hostname: "{{project.name if project is defined else 'noname'}}-vs1"

  consul:
     mode: 'server'

  limits:
    cpu: 3
    memory: 1024

  vagrant:
     box:
       name: "vstand-p8"
       url: "{{ daas_repository_dir }}/vagrant/boxes/p8/vstand.box"

  gitlab:
    url: "http://192.168.1.76:30080/"
    runner_registration_token: "xsmZtVJpEhbuxTp1JAys"
    runner_download_url: "{{ daas_repository_dir}}/gitlab-runner/gitlab-runner-linux-amd64"
