#!/bin/sh

[ -n "$DAAS_DEBUG" ] && set -x
[ -z "$DAAS_DATADIR" ] && DAAS_DATADIR='..'

. $DAAS_DATADIR/modules.d/.daas-common

module_usage() {
    echo "Run docker-compose for this project. Run 'docker-compose --help' for help"
}

module_help() {
    module_usage
}

module_error() {
    echo "$1"
    exit 1
}

run_compose() {
    WORKDIR=$(pwd)
    prepare_environment || return 1
    cd $DAAS_OUTDIR
    docker-compose $@
    RET=$?
    cd $WORKDIR
    return $RET
}

[ -z "$1" ] && module_help && exit 1

case $1 in
    -h | --help | help)
        module_help
        exit 0
        ;;
    --usage | usage)
        module_usage
        exit 0
        ;;
    *)
        run_compose $@
        exit $?
        ;;
esac
