#!/bin/sh

[ -n "$DAAS_DEBUG" ] && set -x
[ -z "$DAAS_DATADIR" ] && DAAS_DATADIR='..'

module_usage() {
    echo "(daas): down services.."
    docker-compose down --help
}

module_help() {
    module_usage
}

case $1 in
    -h | --help | help)
        module_help
        exit 0
        ;;
    --usage | usage)
        module_usage
        exit 0
        ;;
    *)
        $DAAS_DATADIR/modules.d/dc down $@
        exit $?
        ;;
esac
