#!/bin/sh

module_usage() {
    module_help
}

module_help() {
    echo "image [command] [params]"
    echo "Command: "
    echo "ls            - list images"
    echo "old N [name]  - list of images older than N days"
    echo "                name - filter name (grep)"
}

module_error() {
    echo "$1"
    exit 1
}

function list_old_images() {
    [ -z "$1" ] && module_error "Unknown 'older days'"
    DAYSAGO="$1"
    FILTER="$2"

    tmpfile=$(mktemp)

    docker images | grep -e 'days ago' | grep -v regis | awk '{print $4 " " $1 " " $3}' > $tmpfile

    while read -r D N ID; do

        if [ -n "$FILTER" ]; then
            echo $N | grep -q "$FILTER" || continue
        fi

        [ "$D" -gt $DAYSAGO ] && echo "$ID $N $D"

    done<$tmpfile

    rm -rf $tmpfile
}

[ -z "$1" ] && module_help && exit 1

case $1 in
    -h | --help | help)
        module_help
        exit 0
        ;;
    --usage | usage)
        module_usage
        exit 0
        ;;

    --ls | ls)
        shift
        docker image ls
        exit $?
        ;;

    --old | old)
        shift
        list_old_images $@
        exit $?
        ;;
esac
