#!/bin/sh

[ -n "$DAAS_DEBUG" ] && set -x
[ -z "$DAAS_DATADIR" ] && DAAS_DATADIR='..'

. $DAAS_DATADIR/modules.d/.daas-common

module_usage() {
    module_help
}

module_help() {
    echo "image [command] [params]"
    echo "Command: "
    echo "ls                                          - list images"
    echo "old N ['days'|'hours'|'months'|'years']     - list of images older than N ['days']. Default: 'days'"
    echo "rm N ['days'|'hours'|'months'|'years'] [-f] - remove images older than N ['days']. Default: 'days'"
    echo "                                              -f - force remove"
}

module_error() {
    echo "$1"
    exit 1
}

function list_old_images() {
    
    [ -n "$2" ] && FILTER="$2" || FILTER='days'

    [ -z "$1" ] && module_error "Unknown number 'older $FILTER ago'"
    DAYSAGO="$1"

    tmpfile=$(mktemp)

    docker images | grep "$FILTER ago" | awk '{print $4 " " $1 " " $3}' > $tmpfile

    while read -r D N ID; do

        [ "$D" -gt $DAYSAGO ] && echo "$ID $N $D"

    done<$tmpfile

    rm -rf $tmpfile
}

function rm_old_images() {
    FORCE=''
    [ "$2" == "-f" ] && FORCE='-f'
    [ "$3" == "-f" ] && FORCE='-f'

    docker image rm $FORCE $(list_old_images $@ | awk '{print $1}')
}

[ -z "$1" ] && module_help && exit 1

case $1 in
    -h | --help | help)
        module_help
        exit 0
        ;;
    --usage | usage)
        module_usage
        exit 0
        ;;

    --ls | ls)
        shift
        docker image ls
        exit $?
        ;;

    --old | old)
        shift
        list_old_images $@
        exit $?
        ;;

    --rm | rm)
        shift
        rm_old_images $@
        exit $?
        ;;
esac
