#!/bin/sh

[ -n "$DAAS_DEBUG" ] && set -x
[ -z "$DAAS_DATADIR" ] && DAAS_DATADIR='..'

. $DAAS_DATADIR/modules.d/.daas-common

[ -z "$DAAS_ANSIBLE_D" ] && DAAS_ANSIBLE_D="$DAAS_DATADIR/ansible.d"
[ -z "$DAAS_ANSIBLE_CONFIG" ] && DAAS_ANSIBLE_CONFIG="$DAAS_ANSIBLE_D/ansible.cfg"
[ -z "$DAAS_ANSIBLE_PRIVATE" ] && DAAS_ANSIBLE_PRIVATE="$HOME/.daas/ansible_private"
STAND_HOST=''
SSH_USER=$USER
DAAS_VSTAND_CONFIG='daas-vstand-config.yml'
DAAS_PROJECT_CONFIG='.daas.yml'
[ -z "$GITLAB_RUNNER_REGISTRATION_TOKEN" ] && GITLAB_RUNNER_REGISTRATION_TOKEN=''

module_usage() {
    echo " "
    echo "Usage: vstand command [options]"
    echo " "
    echo "Commads for host machine:"
    echo "-------------------------"
    echo "prepare hostname [ext options] -- [ansible options]                  - setup host for stands control"
    echo " "
    echo "Commands for virtual stand:"
    echo "---------------------------"
    echo "create hostname [ project.yml ] [ext options] -- [ansible options]   - create vstand for project"
    echo "                                                                       Default project file '.daas.yml'"
    echo "setup hostname [ project.yml ] [ext options] -- [ansible options]    - prepare vstand for project"
    echo "                                                                       Default project file '.daas.yml'"
    echo "show [defaults|config] [ project.yml ]                               - Show config parameters"
    echo "                                                                       default - show default parameters"
    echo "                                                                       configs - show merged parameters"
    echo "Ext options:"
    echo "------------"
    echo "-c|--config vstand-config.yml    - config (yaml) for vstand"
    echo "-v|--variable var=val            - added variable for ansible (can be used multiple times)"
    echo "--gitlab-token token             - gitlab-runner registration token for gitlab. Default use from vstand config file"
    echo " "
}

module_help() {
    module_usage
}

module_error() {
    echo "ERROR: $1"
    exit 1
}

split_options() {
    [ -z "$PROG" ] && PROG="${0##*/}"

    DAAS_ANSIBLE_USER_VARS=''

    TEMP=$(getopt -n $PROG -o c:,u:,v: -l config:,user:,variable:,gitlab-token: -- "$@") || return 1
    eval set -- "$TEMP"

    while :; do
        case "$1" in
            -u | --user)
                shift
                [ "$1" == '--' ] && break
                SSH_USER="$1"
                ;;
            -c | --config)
                shift
                [ "$1" == '--' ] && break
                DAAS_VSTAND_CONFIG="$1"
                ;;
            -v | --variable)
                shift
                [ "$1" == '--' ] && break
                DAAS_ANSIBLE_USER_VARS="${DAAS_ANSIBLE_USER_VARS} -e $1"
                ;;
            --gitlab-token)
                shift
                [ "$1" == '--' ] && break
                GITLAB_RUNNER_REGISTRATION_TOKEN="$1"
                ;;
            --)
                shift
                break
                ;;
        esac
        shift
    done

    OTHER=$@
}

prepare_ansible_environment() {

    export ANSIBLE_CONFIG=$DAAS_ANSIBLE_CONFIG

    DAAS_ANSIBLE_EXTRA_ARGS="$DAAS_ANSIBLE_EXTRA_ARGS"

    local ANSIBLE_ENV="-e daas_vars_files=$(realpath $DAAS_VSTAND_CONFIG) -e daas_data_dir=$(realpath $DAAS_DATADIR) -e daas_ansible_dir=$(realpath $DAAS_ANSIBLE_D)"

    DAAS_ANSIBLE_EXTRA_ARGS="$DAAS_ANSIBLE_EXTRA_ARGS $ANSIBLE_ENV"
}

check_config_files() {

    local FUNC="$1"

    if ! test -f "$DAAS_VSTAND_CONFIG"; then
        module_error "($FUNC): Not found vstand config file '$DAAS_VSTAND_CONFIG'"
    fi

    if ! test -f "$DAAS_PROJECT_CONFIG"; then
        module_error "($FUNC): Not found project config file '$DAAS_PROJECT_CONFIG'"
    fi
}

do_prepare_host() {
    echo "Setup stand '$STAND_HOST'.."

    check_config_files "prepare"

    local INVFILE=$(mktemp)
    echo "[vstands]" >$INVFILE
    echo "new-vstand ansible_host=$STAND_HOST" >>$INVFILE

    prepare_ansible_environment

    ansible-playbook -i $INVFILE ${DAAS_ANSIBLE_EXTRA_ARGS} ${DAAS_ANSIBLE_USER_VARS} --ssh-extra-args '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' -l new-vstand $@ ${DAAS_ANSIBLE_D}/playbooks/host-setup.yml

    RET=$?
    rm -rf $INVFILE
    return $RET
}

do_create_stand() {

    check_config_files "create"

    PROJECT_NAME=$(daas-project name -c $DAAS_PROJECT_CONFIG)
    echo "Create stand for '$PROJECT_NAME' on '$STAND_HOST'.."
    local INVFILE=$(mktemp)
    echo "[vstands]" >$INVFILE
    echo "vstand ansible_host=$STAND_HOST" >>$INVFILE

    prepare_ansible_environment

    [ -n "$DAAS_DEBUG" ] && ANSIBLE_DEBUG="-vvv" || ANSIBLE_DEBUG=''

    DAAS_ANSIBLE_EXTRA_ARGS="${DAAS_ANSIBLE_EXTRA_ARGS} -e daas_project_file=$(realpath $DAAS_PROJECT_CONFIG)"

    local DAAS_NEWSTAND_IP=$(mktemp)
    DAAS_ANSIBLE_EXTRA_ARGS="${DAAS_ANSIBLE_EXTRA_ARGS} -e daas_newstand_ip_file=$DAAS_NEWSTAND_IP"

    ansible-playbook -i $INVFILE ${DAAS_ANSIBLE_EXTRA_ARGS} ${DAAS_ANSIBLE_USER_VARS} --ssh-extra-args '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' -l vstand $ANSIBLE_DEBUG $@ ${DAAS_ANSIBLE_D}/playbooks/vstand-create.yml

    RET=$?
    rm -rf $INVFILE
    echo "NEW STAND IP: $(cat $DAAS_NEWSTAND_IP)"
    rm -rf $DAAS_NEWSTAND_IP

    return $RET
}

do_setup_stand() {

    check_config_files "setup"

    PROJECT_NAME=$(daas-project name -c $DAAS_PROJECT_CONFIG)
    echo "Prepare stand for '$PROJECT_NAME' on '$STAND_HOST'.."

    if ! ping -c 1 -w 1 $STAND_HOST 1>/dev/null 2>/dev/null; then
        echo "ERROR: '$STAND_HOST' does not respond"
        return 1
    fi

    local INVFILE=$(mktemp)
    echo "[vstands]" >$INVFILE
    echo "vstand ansible_host=$STAND_HOST" >>$INVFILE

    prepare_ansible_environment

    [ -n "$DAAS_DEBUG" ] && ANSIBLE_DEBUG="-vvv" || ANSIBLE_DEBUG=''

    DAAS_ANSIBLE_EXTRA_ARGS="${DAAS_ANSIBLE_EXTRA_ARGS} -e daas_project_file=$(realpath $DAAS_PROJECT_CONFIG)"

    [ -n "$GITLAB_RUNNER_REGISTRATION_TOKEN" ] && DAAS_ANSIBLE_EXTRA_ARGS="${DAAS_ANSIBLE_EXTRA_ARGS} -e gitlab_runner_registration_token=$GITLAB_RUNNER_REGISTRATION_TOKEN"

    ansible-playbook -i $INVFILE ${DAAS_ANSIBLE_EXTRA_ARGS} ${DAAS_ANSIBLE_USER_VARS} --ssh-extra-args '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' -l vstand $ANSIBLE_DEBUG $@ ${DAAS_ANSIBLE_D}/playbooks/vstand-setup.yml

    RET=$?
    rm -rf $INVFILE

    return $RET
}

do_show_configs() {

    if [ "$SHOW_COMMAND" == "defaults" ]; then
        DAAS_VSTAND_CONFIG="$DAAS_ANSIBLE_D/daas-dummy-config.yml"
        DAAS_PROJECT_CONFIG="$DAAS_VSTAND_CONFIG"
    fi

    check_config_files

    PROJECT_NAME=$(daas-project name -c $DAAS_PROJECT_CONFIG)

    local INVFILE=$(mktemp)
    echo "[vstands]" >$INVFILE
    echo "vstand ansible_host=localhost" >>$INVFILE

    prepare_ansible_environment

    [ -n "$DAAS_DEBUG" ] && ANSIBLE_DEBUG="-vvv" || ANSIBLE_DEBUG=''

    DAAS_ANSIBLE_EXTRA_ARGS="${DAAS_ANSIBLE_EXTRA_ARGS} -e daas_project_file=$(realpath $DAAS_PROJECT_CONFIG)"

    [ -n "$GITLAB_RUNNER_REGISTRATION_TOKEN" ] && DAAS_ANSIBLE_EXTRA_ARGS="${DAAS_ANSIBLE_EXTRA_ARGS} -e gitlab_runner_registration_token=$GITLAB_RUNNER_REGISTRATION_TOKEN"

    case $SHOW_COMMAND in
        config)
            ansible-playbook -i $INVFILE ${DAAS_ANSIBLE_EXTRA_ARGS} ${DAAS_ANSIBLE_USER_VARS} --ssh-extra-args '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' -l vstand $ANSIBLE_DEBUG $@ ${DAAS_ANSIBLE_D}/playbooks/vstand-show-config.yml
            ;;
        defaults)
            ansible-playbook -i $INVFILE ${DAAS_ANSIBLE_EXTRA_ARGS} ${DAAS_ANSIBLE_USER_VARS} --ssh-extra-args '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' -l vstand $ANSIBLE_DEBUG $@ ${DAAS_ANSIBLE_D}/playbooks/vstand-show-defaults.yml
            ;;
        *)
            echo "Unknown command '$SHOW_COMMAND' for show. Use: daas vstand --help for help "
            RET=1
            ;;
    esac

    [ -z "$RET" ] && RET=$?
    rm -rf $INVFILE
    return $RET
}

[ -z "$1" ] && module_help && exit 1

case $1 in
    -h | --help | help)
        module_help
        exit 0
        ;;
    --usage | usage)
        module_usage
        exit 0
        ;;
    --prepare | prepare)
        shift
        split_options $@
        eval set -- "$OTHER"

        [ -z "$1" ] && module_error "Unknown hostname. Use: daas vstand --help for help"
        STAND_HOST="$1"
        shift
        do_prepare_host $@
        exit $?
        ;;
    --create | create)
        shift
        split_options $@
        eval set -- "$OTHER"

        [ -z "$1" ] && module_error "Unknown hostname. Use: daas vstand --help for help"
        STAND_HOST="$1"
        shift
        [ -n "$1" ] && DAAS_PROJECT_CONFIG="$1" && shift

        do_create_stand $@
        exit $?
        ;;
    --setup | setup)
        shift
        split_options $@
        eval set -- "$OTHER"

        [ -z "$1" ] && module_error "Unknown hostname. Use: daas vstand --help for help"
        STAND_HOST="$1"
        shift
        [ -n "$1" ] && DAAS_PROJECT_CONFIG="$1" && shift

        do_setup_stand $@
        xit $?

        ;;
    --show|show)
        shift
        [ -z "$1" ] && module_error "Unknown show command (defaults|config). Use: daas vstand --help for help"
        SHOW_COMMAND="$1"
        shift

        split_options $@
        eval set -- "$OTHER"

        [ -n "$1" ] && DAAS_PROJECT_CONFIG="$1" && shift

        do_show_configs $@
        exit $?
        ;;
    *)
        module_usage && exit 1
        ;;
esac

echo "Run ansible $@"
