#!/usr/bin/env python
# -*- coding: utf-8 -*-

from jinja2 import Environment, FileSystemLoader
import yaml

from itertools import groupby
import sys
import os
import socket
import shutil
import errno
from distutils.dir_util import copy_tree

daas_user_dirs = ['./', '.daas']
daas_system_dirs = ['/usr/share/daas']

FORMAT_VERSION = '0.3'

DEFAULT_LOGDB_SERVICE_IP = 250


def check_arg_param(param):
    plist = list()
    if isinstance(param, list):
        plist = param
    else:
        plist.append(param)

    for i in range(0, len(sys.argv)):
        if sys.argv[i] in plist:
            return True

    return False


def get_arg_param(param, defval=""):
    plist = list()
    if isinstance(param, list):
        plist = param
    else:
        plist.append(param)

    for i in range(0, len(sys.argv)):
        if sys.argv[i] in plist:
            if i + 1 < len(sys.argv):
                return sys.argv[i + 1]
            else:
                break

    return defval


def mkdir_p(dpath):
    try:
        os.makedirs(dpath)
    except OSError as e:
        if e.errno != errno.EEXIST:
            raise


def check_static_network(project):
    if 'networks' not in project:
        return False

    for netname in project['networks']:
        net = project['networks'][netname]
        if net and 'subnet' in net:
            return True

    return False


def is_static_network(project):
    if 'static_network' not in project:
        project['static_network'] = check_static_network(project)

    return project['static_network']


def make_ip(subnet, ip):
    return "%s.%s" % (subnet, ip)


def make_host_item(nodename, ip):
    h = dict()
    h['node_name'] = nodename
    h['ip'] = ip
    return h


def sorted_networks(project):
    if 'networks' not in project:
        return list()

    netlist = list()
    klist = sorted(project['networks'].keys())
    networks = project['networks']
    for n in klist:
        net = dict()
        net['name'] = n

        if is_static_network(project):
            if 'subnet' not in networks[n]:
                print "ERROR: Unknown subnet for %s" % str(n)
                exit(1)

            net['subnet'] = networks[n]['subnet']
            if 'gateway' in networks[n]:
                net['gateway'] = networks[n]['gateway']

        netlist.append(net)

    return netlist


def add_host(project, name, ip):
    hosts = list()
    num = 1
    for net in project['sorted_networks']:
        if num == 1:
            hosts.append(make_host_item("%s r1_%s" % (name, name), make_ip(net['subnet'], ip)))
        else:
            hosts.append(make_host_item("r%d_%s" % (num, name), make_ip(net['subnet'], ip)))
        num = num + 1

    return hosts


def make_hosts(project):
    hosts_list = list()

    if is_static_network(project):
        for groupname, group in project['groups'].items():
            if 'nodes' not in group:
                continue

            for nodename, node in group['nodes'].items():
                hosts_list = hosts_list + add_host(project, nodename, node['ip'])

    hosts_list.sort()
    return hosts_list


def get_list(src, name):
    if name in src and len(src[name]) > 0:
        return src[name]

    return list()


def get_apt_param(params, name):
    if not params:
        return list()

    if 'apt' not in params:
        return list()

    if name not in params['apt']:
        return list()

    if not params['apt'][name]:
        return list()

    return params['apt'][name]


def get_param(project, group, node, name):
    if node and name in node:
        return node[name]

    if group and name in group:
        return group[name]

    if project and name in project:
        return project[name]

    return None


def make_copy_params(src):
    """
    split 'copy' format '[mode]src:dest' to param['src'],param['dest'],param['chmod']
    :param src: list of string 'copy'
    :return: list of {'src':.., 'dest':..., 'chmod':..}
    """

    if not src or len(src) == 0:
        return

    res = list()
    for s in src:
        chmod = None
        if s.startswith('['):
            pos = str(s).find(']', 1)
            if pos:
                chmod = s[1:pos]
            s = s[pos + 1:]

        tmp = s.split(':')
        if len(tmp) > 1:
            p = dict()
            p['src'] = tmp[0]
            p['dest'] = tmp[1]
            if chmod:
                p['chmod'] = chmod
            res.append(p)

    return res


def make_unique_list(srclist):
    # с сохранением порядка
    return [el for el, _ in groupby(srclist)]

    # без сохранения порядка
    # return list(set(srclist))

def get_vnc_ports(node):
    ret = list()
    if 'vnc_port' in node:
        p = '%s:%s' % (node['vnc_port'], node['vnc_port'])
        ret.append(p)
    return ret


def get_vnc_environment(node):
    ret = list()
    if 'vnc_port' in node:
        p = 'VNC_PORT=%s' % node['vnc_port']
        ret.append(p)
    return ret


def replace_env(text):
    if not text:
        return text

    if len(text) == 0:
        return text

    ret = text
    for ename in os.environ.keys():
        param = '$%s' % ename
        if param in text:
            ret = ret.replace(param, os.environ[ename])

    return ret


def create_node(project, group, node):
    c = dict(node)

    if is_static_network(project):
        for net in project['sorted_networks']:
            c[net['name']] = make_ip(net['subnet'], node['ip'])

    imagename = get_param(project, group, node, 'image')
    if not imagename:
        raise ValueError('Unknown image for %s' % node['node_name'])

    c['Dockerfile.tpl'] = get_image_template(imagename)
    c['image'] = imagename
    c['image_name'] = replace_env(make_image_name(project, get_image_name(imagename)))

    c['node_compose_template'] = get_param(project, group, node, 'node_compose_template')
    if not c['node_compose_template']:
        c['node_compose_template'] = 'docker-compose-simple.yml.tpl'

    if 'hostname' in node:
        c['hostname'] = replace_env(node['hostname'])

    if 'context' in node:
        c['context'] = replace_env(node['context'])
    else:
        c['context'] = node['node_name']

    c['start_command'] = get_param(project, group, node, 'start_command')
    c['apt'] = dict()
    c['apt']['sources'] = list()
    c['apt']['packages'] = list()
    c['apt']['sources_list_filename'] = None

    if 'ssh_port' in node:
        if 'ssh_internal_port' not in c:
            c['ssh_internal_port'] = 22

    if 'skip_compose' in group:
        c['skip_compose'] = 'yes'

    c['devices'] = make_unique_list(get_list(project, 'devices')
                                    + get_list(group, 'devices')
                                    + get_list(node, 'devices'))

    c['volumes'] = make_unique_list(get_list(project, 'volumes')
                                    + get_list(group, 'volumes')
                                    + get_list(node, 'volumes'))

    c['cap_add'] = make_unique_list(get_list(project, 'cap_add')
                                    + get_list(group, 'cap_add')
                                    + get_list(node, 'cap_add'))

    c['ports'] = make_unique_list(get_list(project, 'ports')
                                  + get_list(group, 'ports')
                                  + get_list(node, 'ports')
                                  + get_vnc_ports(node))

    c['environment'] = make_unique_list(get_list(project, 'environment')
                                        + get_list(group, 'environment')
                                        + get_list(node, 'environment')
                                        + get_vnc_environment(node))

    c['env_file'] = make_unique_list(get_list(project, 'env_file')
                                     + get_list(group, 'env_file')
                                     + get_list(node, 'env_file'))

    copy_list = make_unique_list(get_list(project, 'copy')
                                 + get_list(group, 'copy')
                                 + get_list(node, 'copy'))

    c['before_command'] = make_unique_list(get_list(project, 'before_command')
                                           + get_list(group, 'before_command')
                                           + get_list(node, 'before_command'))

    c['copy'] = make_copy_params(copy_list)

    # global + parameters for type + local
    c['apt']['sources'] = make_unique_list(get_apt_param(project, 'sources')
                                           + get_apt_param(group, 'sources')
                                           + get_apt_param(node, 'sources'))

    if len(c['apt']['sources']) > 0:
        c['apt']['sources_list_filename'] = 'sources.list'

    c['apt']['packages'] = make_unique_list(get_apt_param(project, 'packages')
                                            + get_apt_param(group, 'packages')
                                            + get_apt_param(node, 'packages'))

    c['labels'] = make_unique_list(get_list(project, 'labels')
                                            + get_list(group, 'labels')
                                            + get_list(node, 'labels'))

    return c


def make_project_nodes(project):
    nodes = list()

    for name, group in project['groups'].items():
        group['group_name'] = name
        nodes = nodes + make_nodes(project, group)

    return nodes


def make_nodes(project, group):
    nlist = list()

    if 'nodes' in group and len(group['nodes']) > 0:
        for name, node in group['nodes'].items():
            node['node_name'] = name
            c = create_node(project, group, node)
            nlist.append(c)

    nlist.sort()
    return nlist


def make_image_name(project, imgname):
    name = "%s-%s" % (project['name'], get_image_name(imgname))
    if len(project['image-registry']) > 0:
        name = "%s/%s" % (project['image-registry'], name)
    if len(project['image-postfix']) > 0:
        name = "%s%s" % (name, project['image-postfix'])

    return name


def get_image_name(iname):
    if os.path.sep not in iname:
        return iname

    return iname.replace(os.path.sep, '.')


def get_image_template(iname):
    if os.path.sep not in iname:
        return 'Dockerfile.%s.tpl' % iname

    dirname = os.path.dirname(iname)
    tname = 'Dockerfile.%s.tpl' % os.path.basename(iname)
    return os.path.join(dirname, tname)


def make_dockerfile(dirname, node, project):
    if not os.path.exists(dirname):
        mkdir_p(dirname)

    dockerfile = os.path.join(dirname, 'Dockerfile')
    with open(dockerfile, 'w') as wfile:
        wfile.write(env.get_template(node['Dockerfile.tpl']).render(node=node, project=project))


def make_novnc_dockerfile(dirname, node, project):
    if 'vnc_port' not in node:
        return

    if not os.path.exists(dirname):
        mkdir_p(dirname)

    dockerfile = os.path.join(dirname, 'Dockerfile.novnc')
    with open(dockerfile, 'w') as wfile:
        wfile.write(env.get_template('Dockerfile.novnc.tpl').render(node=node, project=project))


def create_apt_configs(node):
    if 'apt' not in node:
        node['apt'] = dict()

    if 'packages' not in node['apt']:
        node['apt']['packages'] = list()

    if 'sources' not in node['apt']:
        node['apt']['sources'] = list()

    node['apt']['sources_list_filename'] = None


def make_nginx_node(dirname, project):
    if not os.path.exists(dirname):
        mkdir_p(dirname)

    if 'nginx' not in project:
        return

    nginx = project['nginx']
    
    if 'port' not in project['nginx']:
       project['nginx']['port'] = '8080'

    if 'internal_port' not in project['nginx']:
       project['nginx']['internal_port'] = '80'
    
    create_apt_configs(nginx)

    if len(nginx['apt']['sources']) > 0:
        nginx['apt']['sources_list_filename'] = 'nginx-sources.list'

    dockerfile = os.path.join(dirname, 'Dockerfile')
    with open(dockerfile, 'w') as wfile:
        wfile.write(env.get_template('Dockerfile.nginx.tpl').render(project=project))

    confile = os.path.join(dirname, '%s-nginx.conf' % project['name'])
    with open(confile, 'w') as wfile:
        wfile.write(env.get_template('nginx.conf.tpl').render(project=project))

    # gen sources list
    if nginx['apt']['sources_list_filename']:
        apt_sourcefile = os.path.join(dirname, nginx['apt']['sources_list_filename'])
        make_apt_sources_list(nginx, apt_sourcefile)

    # make logdb configs
    logdbconfdir = os.path.join(dirname, 'logdb.d')
    if not os.path.exists(logdbconfdir):
        mkdir_p(logdbconfdir)

    if project['required_logdb']:
        logdb_upstream = os.path.join(logdbconfdir, '%s-logdb-upstream.conf' % project['name'])
        with open(logdb_upstream, 'w') as wfile:
            wfile.write(env.get_template('logdb-upstream.conf.tpl').render(project=project))

        logdb_location = os.path.join(logdbconfdir, '%s-logdb-location.conf' % project['name'])
        with open(logdb_location, 'w') as wfile:
            wfile.write(env.get_template('logdb-location.conf.tpl').render(project=project))

    # copy addons
    copy_addons(dirname)


def make_logdb_node(dirname, project):
    if 'logdb' not in project:
        return

    logdb = project['logdb']

    if not os.path.exists(dirname):
        mkdir_p(dirname)

    create_apt_configs(logdb)

    if len(logdb['apt']['sources']) > 0:
        logdb['apt']['sources_list_filename'] = 'logdb-sources.list'

    if is_static_network(project):
        if 'ip' not in logdb:
            logdb['ip'] = DEFAULT_LOGDB_SERVICE_IP

        for net in project['sorted_networks']:
            logdb[net['name']] = make_ip(net['subnet'], logdb['ip'])

    dockerfile = os.path.join(dirname, 'Dockerfile')
    with open(dockerfile, 'w') as wfile:
        wfile.write(env.get_template('Dockerfile.logdb.tpl').render(project=project))

    # gen sources list
    if logdb['apt']['sources_list_filename']:
        apt_sourcefile = os.path.join(dirname, logdb['apt']['sources_list_filename'])
        make_apt_sources_list(logdb, apt_sourcefile)

    # make logdb-conf.xml
    confile = os.path.join(dirname, '%s-logdb-conf.xml' % project['name'])
    with open(confile, 'w') as wfile:
        wfile.write(env.get_template('logdb-conf.xml.tpl').render(project=project).encode('utf-8'))

    # copy addons
    copy_addons(dirname)

    # create logdb directory
    dbdir = os.path.join(dirname, 'logdb')
    if not os.path.exists(dbdir):
        mkdir_p(dbdir)


def make_config_for_nginx(basedirname, node, project):
    if 'novnc_port' not in node:
        return

    confdir = os.path.join(basedirname, 'vnc.d')

    if not os.path.exists(confdir):
        mkdir_p(confdir)

    loc_confname = '%s-location.conf' % node['node_name']

    loc_outfile = os.path.join(confdir, loc_confname)
    with open(loc_outfile, 'w') as wfile:
        wfile.write(env.get_template('novnc-location.conf.tpl').render(node=node, project=project))

    upstream_confname = '%s-upstream.conf' % node['node_name']
    upstream_outfile = os.path.join(confdir, upstream_confname)
    with open(upstream_outfile, 'w') as wfile:
        wfile.write(env.get_template('novnc-upstream.conf.tpl').render(node=node, project=project))


def make_apt_sources_list(node, filename, tplname='sources.list.tpl'):
    with open(filename, 'w') as wfile:
        wfile.write(env.get_template(tplname).render(node=node))


def copy_addons(todirname):
    # Формируем список в порядке приоритета
    # "пользовательские файлы, приоритетнее плагинов (dir.d)
    # плагины приоритетнее системных
    # Поэтому мы копируем в порядке возрастания приоритета, чтобы каждое следующее копирование
    # затирало предыдущий файл, если он уже есть
    # ----------------------
    cdirs = list()
    for d in reversed(daas_system_dirs):
        cdirs.append(os.path.join(d, "addons"))

    for d in reversed(daas_system_dirs):
        cdirs.append(os.path.join(d, "addons.d"))

    if 'DAAS_ADDONS_DIR' in os.environ:
        cdirs.append(os.environ['DAAS_ADDONS_DIR'])

    for d in reversed(daas_user_dirs):
        cdirs.append(os.path.join(d, "addons"))

    for addonsdir in cdirs:
        if os.path.exists(addonsdir):
            for f in os.listdir(addonsdir):
                src = os.path.join(addonsdir, f)
                dest = os.path.join(todirname, f)
                if not os.path.isdir(src):
                    shutil.copy(src, dest)
                else:
                    copy_tree(src, dest)


def usage():
    print "daas-project command [ -c|--confile project.yml ] [options]"
    print "Commands:"
    print "---------"
    print "gen                        - Generate files for docker-compose"
    print "image-list                 - Print list of images (bash format)"
    print "image-name nodename        - Print image name for nodename"
    print "docker-add-host            - Print extra hosts for docker (--add-host format)"
    print "ssh-port [user@]nodename   - Print ssh-port for nodename"
    print "name                       - Print project name"

    print
    print "Options:"
    print "---------"
    print "--output outdir         - generate configs to 'outdir'. Default: 'daas-projectname'"
    print "--image-registry name   - docker registry name to use in image name ([registry-name]/image-name)"
    print "--image-postfix name    - postfix for use in image name (image-name[postfix])"
    print "See 'Environment'.."
    print ""
    print "-q|--quite              - silent mode"

    print
    print "Environment:"
    print "------------"
    print "DAAS_OUTDIR - output directory for generate files. Default: 'daas-projectname'"
    print "   supported variables:"
    print "      {PROJECT} - replace to project name. Example: DAAS_OUTDIR='{PROJECT}-my-postfix' --> 'projectname-my-postfix'"
    print ""
    print "DAAS_TEMPLATES_DIR     - directory with templates"
    print "DAAS_ADDONS_DIR       - directory with addons"
    print "DAAS_IMAGE_REGISTRY   - see --image-registry"
    print "DAAS_IMAGE_POSTFIX    - see --image-postfix"
    print "DAAS_VSTAND_HOSTNAME  - set stand hostname. Default: use hostinfo"


if __name__ == "__main__":

    if check_arg_param(['--help', '-h']):
        usage()
        exit(0)

    if len(sys.argv) < 2:
        usage()
        exit(-1)

    cmd = sys.argv[1].strip().lower()

    tpldirs = list()
    # добавляем в порядке приоритета

    # пользовательские
    for d in daas_user_dirs:
        tpldirs.append(os.path.join(d, 'templates'))

    if 'DAAS_TEMPLATES_DIR' in os.environ:
        tpldirs.append(os.environ['DAAS_TEMPLATES_DIR'])

    # плагины 'dir.d')
    for d in daas_system_dirs:
        tpldirs.append(os.path.join(d, 'templates.d'))
    # системные каталоги
    for d in daas_system_dirs:
        tpldirs.append(os.path.join(d, 'templates'))

    env = Environment(
        loader=FileSystemLoader(tpldirs)
    )

    confile = get_arg_param(['--confile', '-c'], '.daas.yml')
    if not os.path.exists(confile):
        print "ERROR: Not found '.daas.yml'. Use [-c|--confile] filename"
        exit(1)

    conf = None
    with open(confile) as stream:
        try:
            conf = yaml.load(stream)
        except yaml.YAMLError as ex:
            print(ex)
            exit(1)

    if 'version' not in conf:
        print "ERROR: Unknown config file format for '%s'. Supported by %s" % (confile, FORMAT_VERSION)
        exit(1)

    if str(conf['version']) != str(FORMAT_VERSION):
        print "ERROR: Unsupported config file format '%s' ('%s'). Must be '%s'" % (
            conf['version'], confile, FORMAT_VERSION)
        exit(1)

    project = conf['project']

    quite = check_arg_param(['--quite', '-q'])

    project['image-registry'] = ''
    if 'DAAS_IMAGE_REGISTRY' in os.environ:
        project['image-registry'] = os.environ['DAAS_IMAGE_REGISTRY']

    project['image-registry'] = get_arg_param(['--image-registry'], project['image-registry'])

    project['image-postfix'] = ''
    if 'DAAS_IMAGE_POSTFIX' in os.environ:
        project['image-postfix'] = os.environ['DAAS_IMAGE_POSTFIX']
    project['image-postfix'] = get_arg_param(['--image-postfix'], project['image-postfix'])

    if 'project_compose_template' not in project:
        project['project_compose_template'] = 'docker-compose.yml.tpl'

    project['sorted_networks'] = sorted_networks(project)
    project['extra_hosts'] = make_hosts(project)
    project['nodes'] = make_project_nodes(project)

    if 'net_name' not in project:
        project['net_name'] = '%s_net' % project['name']

    if 'DAAS_VSTAND_HOSTNAME' in os.environ:
        project['stand_hostname'] = os.environ['DAAS_VSTAND_HOSTNAME']
    else:
        project['stand_hostname'] = socket.gethostbyaddr(socket.gethostname())[0]

    # check require 'nginx'
    project['required_nginx'] = False
    if 'nginx' in project and 'any' in project['nginx'] and len(project['nginx']['any']) > 0:
        project['required_nginx'] = True

#    for node in project['nodes']:
#        if 'novnc_port' in node:
#            project['required_nginx'] = True
#            project['nginx']['vnc'] = True
#            break

    # check require 'logdb'
    project['required_logdb'] = False
#    if 'logdb' in project and 'disable' not in project['logdb']:
#        for node in project['nodes']:
#            if 'logservers' in node and len(node['logservers']) > 0:
#                project['required_logdb'] = True
#                project['nginx']['logdb'] = True
#                break

#    if project['required_logdb']:
#        project['required_nginx'] = True

    if project['required_nginx'] and 'nginx' not in project:
        project['nginx'] = dict()
        project['nginx']['port'] = '8080'
        project['nginx']['intrernal_port'] = '80'

    if project['required_logdb'] and 'logdb' not in project:
        project['logdb'] = dict()

    if project['required_logdb'] and 'port' not in project['logdb']:
        project['logdb']['port'] = 42000  # <-- просто какое-то число

    # [command]: docker-add-host
    if cmd == 'docker-add-host':
        ret = ''
        for h in project['extra_hosts']:

            # split if nodename="node1 node2 node3"
            hh = h['node_name'].split(' ')
            if len(hh) > 1:
                for n in hh:
                    ret = '--add-host %s:%s %s' % (n, h['ip'], ret)
            else:
                ret = '--add-host %s:%s %s' % (h['node_name'], h['ip'], ret)
        print ret.strip()
        exit(0)

    # [command]: image-list
    if cmd == 'image-list':
        img_list = list()
        s = ''
        for node in project['nodes']:
            img_list.append(node['image_name'])

        uniq_list = make_unique_list(img_list)
        for n in uniq_list:
            s = '%s %s' % (s, n)

        print s.strip()
        exit(0)

    # [command]: image-name
    if cmd == 'image-name':
        nodename = get_arg_param(['image-name'])
        if len(nodename) == 0:
            print "(image-name): Unknown node name. Use -h for help"
            exit(1)

        for n in project['nodes']:
            if n['node_name'] == nodename:
                print n['image_name']
                exit(0)

        print "(image-name): ERROR: Not found node '%s'" % nodename
        exit(1)

    if cmd == 'ssh-port':
        nodename = get_arg_param(['ssh-port'])
        if '@' in nodename:
            tmp = nodename.split('@')
            nodename = tmp[1]

        if len(nodename) == 0:
            print "(ssh): Unknown node name. Use -h for help"
            exit(1)

        for node in project['nodes']:
            if node['node_name'] == nodename:
                if 'ssh_port' in node:
                    print node['ssh_port']
                    exit(0)
                else:
                    print "Unknown ssh port for node '%s'" % nodename
                    exit(1)

        print "(ssh): ERROR: Not found node '%s'" % nodename
        exit(1)

    if cmd == 'name':
        print project['name']
        exit(0)

    # --------------- command: GEN ------------------

    if cmd != 'gen':
        print "Unknown command. Use -h for help"
        exit(1)

    outdir = 'daas-%s' % project['name']

    if 'DAAS_OUTDIR' in os.environ:
        outdir = os.environ['DAAS_OUTDIR']
        if '{PROJECT}' in outdir:
            outdir = outdir.replace('{PROJECT}', project['name'])

    outdir = get_arg_param(['--output'], outdir)

    if not os.path.exists(outdir):
        mkdir_p(outdir)

    # make logdb container
    if project['required_logdb']:
        logdbdir = os.path.join(outdir, 'logdb')
        make_logdb_node(logdbdir, project)

    # make nginx container
    nginxdir = os.path.join(outdir, 'nginx')
    if project['required_nginx']:
        make_nginx_node(nginxdir, project)

    # make docker-compose.yml
    dc_file = os.path.join(outdir, 'docker-compose.yml')
    with open(dc_file, 'w') as wfile:
        wfile.write(env.get_template(project['project_compose_template']).render(project=project))

    # make directories and configs
    for n in project['nodes']:
        dirname = os.path.join(outdir, n['context'])
        if not os.path.exists(dirname):
            mkdir_p(dirname)

        # make conf for nginx
        make_config_for_nginx(nginxdir, n, project)

        # gen sources list
        if n['apt']['sources_list_filename']:
            apt_sourcefile = os.path.join(dirname, n['apt']['sources_list_filename'])
            make_apt_sources_list(n, apt_sourcefile)

        # make Dockerfile
        make_dockerfile(dirname, n, project)

        # make Dockerfile.novnc
        make_novnc_dockerfile(dirname, n, project)

        # copy addons
        copy_addons(dirname)

        # generate simple compose file
        if 'skip_compose' in n:
            dc_file = os.path.join(dirname, 'docker-compose.yml')
            with open(dc_file, 'w') as wfile:
                wfile.write(env.get_template(n['node_compose_template']).render(project=project, node=n))
                wfile.write("\n")

    if not quite:
        print outdir
